### PR TITLE
fix:command fixed to include coverage in tox tests

### LINKED ISSUE #59: Fix coverage detection
Currently tests don't collect coverage data and print a warning about that. Running pytest directly works while running tox doesn't. I feel like it's because of the path problem currently hidden by `PY_IGNORE_IMPORTMISMATCH=1` (as coverage collection should depend on file paths), but I don't know how to fix it.

### PR DESCRIPTION
**Pull request by swayam0322**
Fixes #59

### CODE REVIEW

**Comment by swayam0322** [comment]
@wRAR Please review this PR

**Comment by wRAR** [comment]
Please explain what did you do and why do you think it fixes what you say it fixes.

**Comment by swayam0322** [comment]
Previously on running tox tests 
```
./home/sam/zyte-common-items/.tox/py310/lib/python3.10/site-packages/coverage/control.py:892: CoverageWarning: No data was collected. (no-data-collected)
  self._warn("No data was collected.", slug="no-data-collected")
```

But upon changing the order of the directories after the flag
```
py.test --cov-report=term-missing:skip-covered --cov-report=html --cov-report= --cov-report=xml --cov=zyte_common_items '--doctest-glob=*.rst' --doctest-modules zyte_common_items docs tests
```
The coverage is tracked in tox tests as well:
```
---------- coverage: platform linux, python 3.10.12-final-0 ----------
Name                                                Stmts   Miss  Cover   Missing
---------------------------------------------------------------------------------
zyte_common_items/_dateutils.py                        18      1    94%   28
zyte_common_items/ae.py                               300     12    96%   41, 66, 68, 134-136, 259-260, 385-387, 405
zyte_common_items/base.py                             106      2    98%   182-183
zyte_common_items/converters.py                        27      1    96%   60
zyte_common_items/items/_compat.py                      7      1    86%   17
zyte_common_items/pages/base.py                        45      1    98%   33
zyte_common_items/pages/job_posting_navigation.py      32      5    84%   37, 41, 45, 49, 53
zyte_common_items/pages/mixins.py                      78      3    96%   54, 108, 113
zyte_common_items/pages/serp.py                        26      4    85%   27, 31, 35, 39
zyte_common_items/pages/social_media_post.py           42      9    79%   32, 36, 40, 44, 48, 52, 56, 60, 64
zyte_common_items/pipelines.py                         43      1    98%   95
zyte_common_items/processors.py                       179      5    97%   55, 177, 202, 204, 361
zyte_common_items/util.py                              39      3    92%   86-94
---------------------------------------------------------------------------------
TOTAL                                                2304     48    98%

47 files skipped due to complete coverage.
Coverage HTML written to dir htmlcov
Coverage XML written to file coverage.xml
```

I am not sure why this works but it works

**Comment by swayam0322** [comment]
@wRAR I think this should work now after adding CODECOV_TOKEN as repository secret 

Coverage on my fork:
image

**Comment by wRAR** [comment]
I don't understand why does the ordering fix the path problem but thanks!

**Comment by Gallaecio** [comment]
Thank you!

**Comment by swayam0322** [comment]
@Gallaecio  Is there a development roadmap for the project? 
Was working to migrate the setup.py to pyproject.toml at the moment

**Pull request merged**
